import { Montserrat } from "next/font/google";
import "./globals.css";
import Loading from "@/components/Loading";

const monty = Montserrat({
  variable: "--font-monty",
  subsets: ["latin"],
  weight: ["900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${monty.variable} antialiased bg-black`}>
        <Loading />
        {children}
      </body>
    </html>
  );
}
